python eval_agents.py --restore_path="./exp/train/sd005_20251116_112018" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=8 --proc_name="ryujm-temp-8 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd005_20251116_112018" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=7 --proc_name="ryujm-temp-7 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd005_20251116_112018" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=6 --proc_name="ryujm-temp-6 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd005_20251116_112018" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=5 --proc_name="ryujm-temp-5 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd005_20251116_112018" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=4 --proc_name="ryujm-temp-4 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd004_20251116_092630" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=8 --proc_name="ryujm-temp-8 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd004_20251116_092630" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=7 --proc_name="ryujm-temp-7 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd004_20251116_092630" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=6 --proc_name="ryujm-temp-6 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd004_20251116_092630" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=5 --proc_name="ryujm-temp-5 --eval_on_cpu=0 --video_to_wandb=1 ; \
python eval_agents.py --restore_path="./exp/train/sd004_20251116_092630" --agent=agents/sshiql.py --agent.ensemble_mode="similarity" --agent.similarity_beta=4 --proc_name="ryujm-temp-4 --eval_on_cpu=0 --video_to_wandb=1
